# PostgreSQL Configuration (Render Database)
spring.datasource.url=${jdbc:postgresql://dpg-d8gtggv7f7vs739m56jg-a:5432/plant_management_nzmc}
spring.datasource.username=${plant_admin}
spring.datasource.password=${3X2xW4kiiOnEHhYgtLpzaz2crH5udcff}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Render Port
server.port=${PORT:8080}

# Gemini API Key
gemini.api.key=${AIzaSyDACj6rcBE8OGZ9rjfLbhAn00s253Of__M}

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB